Update of log function and log_and_run function in bin/muset

diff --git a/bin/muset b/bin/muset
--- a/bin/muset
+++ b/bin/muset
@@ -11,20 +11,32 @@ SCRIPT_DIR=$(dirname $(readlink -f $0))
 # Ensure to use the kmat_tools executable within the same folder of this script
 export PATH="${SCRIPT_DIR}${PATH:+:${PATH}}"
 
-SCRIPT_NAME=$(basename \$0)
+SCRIPT_NAME=$(basename $0)
 TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
-LOG_FILE="${SCRIPT_DIR}/${SCRIPT_NAME}_${TIMESTAMP}.log"
+LOG_FILE="./${SCRIPT_NAME}_${TIMESTAMP}.log"
 
-# Ensure log directory exists
-mkdir -p "${LOG_DIR}"
+# Define the log function
+log() {
+    local message="$1"
+    local timestamp=$(date +"[%Y-%m-%d %H:%M:%S.%3N]")
+    echo "${timestamp} ${message}" | tee -a "${LOG_FILE}"
+}
 
-# Redirect stdout and stderr to log file
-exec > >(tee -a "${LOG_FILE}") 2>&1
-
-# Function to log and run commands
+# Define the log_and_run function
 log_and_run() {
-    echo "[COMMAND]:: Running: $@" | tee -a "${LOG_FILE}"
-    "$@"
+    log "[COMMAND]:: Running: $@"
+    {
+        "$@" 2>&1 | while IFS= read -r line
+        do
+            log "$line"
+        done
+        # Check exit status of the command
+        if [ ${PIPESTATUS[0]} -ne 0 ]; then
+            log "Command failed with exit status ${PIPESTATUS[0]}"
+            exit 1  # Exit the script if the command fails
+        fi
+
+    }
 }
 
 # SETTING DEFAULT PARAMETERS
@@ -114,7 +126,7 @@ while getopts ":k:t:u:a:i:n:N:f:F:r:o:m:shV" opt; do
        ;;
     i) input_matrix="${OPTARG}"
        if [ ! -f "${input_matrix}" ] || [ ! -s "${input_matrix}" ]; then
-           echo "ERROR: Input matrix \"${input_matrix}\" is not a file or is empty" >&2
+           log "ERROR: Input matrix \"${input_matrix}\" is not a file or is empty"
            exit 1
        fi
        skip_matrix_construction=true
@@ -123,40 +135,40 @@ while getopts ":k:t:u:a:i:n:N:f:F:r:o:m:shV" opt; do
        ;;
     n)
        if [ -n "$param_n" ]; then
-           echo "ERROR: Cannot combine -n with -f" >&2
-           echo "Try 'muset -h' for more information." >&2
+           log "ERROR: Cannot combine -n with -f"
+           log "Try 'muset -h' for more information."
            exit 1
        fi
        if ! is_integer "${OPTARG}"; then
-           echo "ERROR: -n argument must be an integer." >&2
+           log "ERROR: -n argument must be an integer."
            exit 1
        fi
        param_n="-n ${OPTARG}"k_len
        ;;
     N)
        if [ -n "$param_N" ]; then
-           echo "ERROR: Cannot combine -N with -F" >&2
-           echo "Try 'muset -h' for more information." >&2
+           log "ERROR: Cannot combine -N with -F"
+           log "Try 'muset -h' for more information."
            exit 1
        fi
        if ! is_integer "${OPTARG}"; then
-           echo "ERROR: -N argument must be an integer." >&2
+           log "ERROR: -N argument must be an integer."
            exit 1
        fi
        param_N="-N ${OPTARG}"
        ;;
     f) 
        if [ -n "$param_n" ]; then
-           echo "ERROR: Cannot combine -f with -n" >&2
-           echo "Try 'muset -h' for more information." >&2
+           log "ERROR: Cannot combine -f with -n"
+           log "Try 'muset -h' for more information."
            exit 1
        fi
        param_n="-f ${OPTARG}"
        ;;
     F) 
        if [ -n "$param_N" ]; then
-           echo "ERROR: Cannot combine -F with -N" >&2
-           echo "Try 'muset -h' for more information." >&2
+           log "ERROR: Cannot combine -F with -N"
+           log "Try 'muset -h' for more information."
            exit 1
        fi
        param_N="-F ${OPTARG}"
@@ -169,18 +181,18 @@ while getopts ":k:t:u:a:i:n:N:f:F:r:o:m:shV" opt; do
        ;;
     s) param_s="-s"
        ;;
-    h) echo "${USAGE}"
+    h) log "${USAGE}"
        exit 0
        ;;
-    V) echo "muset v${MUSET_VERSION}"
+    V) log "muset v${MUSET_VERSION}"
        exit 0
        ;;
-    :) echo -e "ERROR: Option -${OPTARG} requires an argument\n" >&2
-       echo "Try 'muset -h' for more information." >&2
+    :) log -e "ERROR: Option -${OPTARG} requires an argument\n"
+       log "Try 'muset -h' for more information."
        exit 1
        ;;
-    \?) echo "Invalid option: -${OPTARG}" >&2
-        echo "Try 'muset -h' for more information." >&2
+    \?) log "Invalid option: -${OPTARG}"
+        log "Try 'muset -h' for more information."
         exit 1
         ;;
     esac
@@ -196,22 +208,22 @@ input_file=""
 if [ "${skip_matrix_construction}" != true ]; then
     
     if [ $# -ne 1 ]; then
-        echo "ERROR: Input file missing." >&2
-        echo "Try 'muset -h' for more information." >&2
+        log "ERROR: Input file missing."
+        log "Try 'muset -h' for more information."
         exit 1
     fi
 
     input_file=$1
 
     if [ ! -f "$input_file" ]; then
-        echo "ERROR: Input file \"${input_file}\" does not exist." >&2
+        log "ERROR: Input file \"${input_file}\" does not exist."
         exit 1
     fi
 fi
 
 # Validate that minimizer length is smaller than k_len
 if [ "$minimizer_length" -ge "$k_len" ]; then
-    echo "Error: Minimizer length (-m) value ($minimizer_length) must be smaller than k-mer size (-k) value ($k_len)." >&2
+    log "Error: Minimizer length (-m) value ($minimizer_length) must be smaller than k-mer size (-k) value ($k_len)."
     exit 1
 fi
 
@@ -221,34 +233,35 @@ if [[ "$output_dir" == */ ]]; then
 fi
 
 # Parameters
-echo "k-mer size (-k): ${k_len}"
-echo "Number of threads (-t): ${thr}"
-echo "Minimum unitig size (-u): ${utg_len}"
-echo "Output directory (-o): ${output_dir}"
-echo "Minimum recurrence (-r): ${rec_min}"
-echo "Minimizer length (-m): ${minimizer_length}"
-echo "Minimum abundance (-a): ${min_kmer_abundance}"
-echo "Input file: ${input_file}"
+log "muset v${MUSET_VERSION}"
+log "k-mer size (-k): ${k_len}"
+log "Number of threads (-t): ${thr}"
+log "Minimum unitig size (-u): ${utg_len}"
+log "Output directory (-o): ${output_dir}"
+log "Minimum recurrence (-r): ${rec_min}"
+log "Minimizer length (-m): ${minimizer_length}"
+log "Minimum abundance (-a): ${min_kmer_abundance}"
+log "Input file: ${input_file}"
 
 # Echo if the matrix construction flag was set
-echo "Skip matrix construction (-s): ${skip_matrix_construction}"
+log "Skip matrix construction (-s): ${skip_matrix_construction}"
 
 # Check for default settings if -n, -N, -f, -F, are not set
 if [ -z "$param_n" ] && [ -z "$param_N" ]; then
     param_n="-f $frac_samples_absent"
     param_N="-F $frac_samples_present"
 elif [ -z "$param_n" ]; then
-    echo "Error: Either -n or -f must be specified." >&2
-    echo "Try 'muset -h' for more information." >&2
+    echo "Error: Either -n or -f must be specified."
+    echo "Try 'muset -h' for more information."
     exit 1
 elif [ -z "$param_N" ]; then
-    echo "Error: Either -N or -F must be specified." >&2
-    echo "Try 'muset -h' for more information." >&2
+    echo "Error: Either -N or -F must be specified."
+    echo "Try 'muset -h' for more information."
     exit 1
 fi
 
-echo "Selected options:"
-echo "Basic filter settings: $param_n $param_N"
+log "Selected options:"
+log "Basic filter settings: $param_n $param_N"
 
 start=$(date +%s%3N)
 
@@ -260,30 +273,30 @@ if [ "${skip_matrix_construction}" != true ]; then
 else
 
     # Warning user that some parameters must be consistent between the input matrix and the ones set for the pipeline
-    echo "WARNING:  You are providing your own input matrix. Please check that the muset parameters"  >&2
-    echo "          k=$k_len (k-mer size), m=$minimizer_length (minimizer size) and a=$min_kmer_abundance (minimum k-mer abundance) you are using" >&2
-    echo "          are consistent with the ones you used for the matrix construction." >&2
+    log "WARNING:  You are providing your own input matrix. Please check that the muset parameters" 
+    log "          k=$k_len (k-mer size), m=$minimizer_length (minimizer size) and a=$min_kmer_abundance (minimum k-mer abundance) you are using"
+    log "          are consistent with the ones you used for the matrix construction."
 
-    # Sanity check on the k-mer lenght. Cheking the length of the first kmer in the matrix is the same of the k_len in muset
+    # Sanity check on the k-mer length. Checking the length of the first kmer in the matrix is the same as the k_len in muset
     matrix_klen=$(awk 'NR==1 {print length($1)}' $input_matrix)
 
     if [ $matrix_klen != $k_len ]; 
     then
-        echo "ERROR: the kmer length of the input matrix you provided is $matrix_klen, while in MUSET is set to $k_len." >&2
+        log "ERROR: the kmer length of the input matrix you provided is $matrix_klen, while in MUSET is set to $k_len."
         exit 1 
     fi
 
-    echo "Skipped matrix construction. Using matrix provided in \"${input_matrix}\""
+    log "Skipped matrix construction. Using matrix provided in \"${input_matrix}\"">&2
     mkdir -p "${output_dir}"
 fi
 
 if [ ! -d "${output_dir}" ]; then
-    echo "Error: The output directory $output_dir does not exist." >&2
+    log "Error: The output directory $output_dir does not exist."
     exit 1
 fi
 
 if [ ! -f "${input_matrix}" ] || [ ! -s "${input_matrix}" ]; then
-    echo "Matrix file \"${input_matrix}\" does not exist or is empty." >&2
+    log "Matrix file \"${input_matrix}\" does not exist or is empty."
     exit 1
 fi
 
@@ -292,7 +305,7 @@ log_and_run kmat_tools filter "${input_matrix}" -a ${min_kmer_abundance} $param_
 
 # Check if filter was too stringent
 if [ ! -s "$output_dir/sorted_filtered_matrix.txt" ]; then
-    echo "Your filters were too stringent. The output file sorted_filtered_matrix.txt is empty." >&2
+    log "Your filters were too stringent. The output file sorted_filtered_matrix.txt is empty."
     exit 1
 fi
 
@@ -307,13 +320,13 @@ log_and_run kmat_tools fafmt -l $utg_len -o $output_dir/unitigs_filtered.fa $out
 
 # Exit if unitig file is empty
 if [ ! -s "$output_dir/unitigs_filtered.fa" ]; then
-    echo "Your filters were too stringent. The output file unitigs.mat is empty." >&2
+    log "Your filters were too stringent. The output file unitigs.mat is empty."
     exit 1
 fi
 
 # Step 4: Build unitig matrix
 log_and_run kmat_tools unitig -k $k_len -m $minimizer_length -o $output_dir/unitigs.mat -t $thr ${param_s} $output_dir/unitigs_filtered.fa $output_dir/sorted_filtered_matrix.txt
-echo "Output unitig matrix written to: " $(readlink -f "${output_dir}/unitigs.mat")
+log "Output unitig matrix written to: " $(readlink -f "${output_dir}/unitigs.mat")
 
-runtime=$((`date +%s%3N`-$start)) && echo "[PIPELINE]::[END]::[$runtime ms]"
+runtime=$((`date +%s%3N`-$start)) && log "[PIPELINE]::[END]::[$runtime ms]"
 exit 0
