fixed default minimum k-mer abundance to 2; added -v option to output version; minor code polishing

diff --git a/bin/muset b/bin/muset
--- a/bin/muset
+++ b/bin/muset
@@ -5,6 +5,8 @@
 
 set -e
 
+MUSET_VERSION="0.2"
+
 SCRIPT_NAME=$(basename $0)
 LOG_DIR="logs"
 TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
@@ -27,7 +29,7 @@ DEFAULT_KSIZE=31
 DEFAULT_WSIZE=14
 DEFAULT_THREADS=4
 DEFAULT_UTG_MIN_SIZE=100
-DEFAULT_MIN_KMER_ABUNDANCE=1
+DEFAULT_MIN_KMER_ABUNDANCE=2
 DEFAULT_NUM_SAMPLES_ABSENT=10
 DEFAULT_NUM_SAMPLES_PRESENT=10
 DEFAULT_FRAC_SAMPLES_ABSENT=0.1
@@ -37,7 +39,7 @@ DEFAULT_MIN_REC=3
 DEFAULT_MINIMIZER_LENGTH=15
 DEFAULT_OUTDIR=output
 
-USAGE='muset v0.2
+USAGE="muset v${MUSET_VERSION}
 
 DESCRIPTION:
    muset - a pipeline for building an abundance unitig matrix from a list of FASTA/FASTQ files.
@@ -46,7 +48,6 @@ USAGE:
    muset [options] INPUT_FILE
 
 OPTIONS:
-   -h         print this help and exit
    -i PATH    skip matrix construction and run the pipeline with a previosuly computed matrix
    -k INT     k-mer size (default: 31)
    -a INT     min abundance to keep a k-mer (default: 2)
@@ -54,20 +55,22 @@ OPTIONS:
    -o PATH    output directory (default: output)
    -r INT     minimum recurrence to keep a k-mer (default: 3)
    -m INT     minimizer length  (default: 15)
-   -n INT     minimum number of zero columns for each k-mer or min number of samples for which a k-mer should be absent (mutually exclusive with -f)
-   -N INT     minimum number of non-zero columns for each k-mer or min number of samples for which a k-mer should be present (mutually exclusive with -F)
-   -f FLOAT   fraction of samples from which a k-mer should be absent (default: 0.1, overrides -n)
-   -F FLOAT   fraction of samples in which a k-mer should be present (default: 0.1, overrides -N)
+   -n INT     minimum number of samples from which a k-mer should be absent (mutually exclusive with -f)
+   -f FLOAT   fraction of samples from which a k-mer should be absent (default: 0.1, mutually exclusive with -n)
+   -N INT     minimum number of samples in which a k-mer should be present (mutually exclusive with -F)
+   -F FLOAT   fraction of samples in which a k-mer should be present (default: 0.1, mutually exclusive with -N)
    -t INT     number of cores (default: 4)
+   -h         print this help and exit
 
 POSITIONAL ARGUMENTS:
     INPUT_FILE   Input file (fof) containing the description of input samples.
                  It is ignored if -i option is used.
 
 NOTES:
-   If neither -n nor -f are provided, -f with its default value is used.
-   If neither -N nor -F are provided, -F with its default value is used.
-'
+   Options -n and -f are mutually exclusive, as well as options -N and -F.
+   When either -n or -f is used, -N or -F must also be provided, and vice versa.
+   If none of the -n, -N, -f, -F options are used the last two options are used with their default values.
+"
 
 # Parsing input options
 k_len=$DEFAULT_KSIZE
@@ -95,11 +98,8 @@ is_integer() {
     return 0
 }
 
-while getopts ":hk:t:u:a:i:n:N:f:F:r:o:m:" opt; do
+while getopts ":k:t:u:a:i:n:N:f:F:r:o:m:hv" opt; do
     case "${opt}" in
-    h) echo "${USAGE}" >&2
-       exit 0
-       ;;
     k) k_len=${OPTARG}
        ;;
     t) thr=${OPTARG}
@@ -108,7 +108,7 @@ while getopts ":hk:t:u:a:i:n:N:f:F:r:o:m:" opt; do
        ;;
     i) input_matrix="${OPTARG}"
        if [ ! -f "${input_matrix}" ] || [ ! -s "${input_matrix}" ]; then
-           echo "Input matrix \"${input_matrix}\" is not a file or is empty" >&2
+           echo "ERROR: Input matrix \"${input_matrix}\" is not a file or is empty" >&2
            exit 1
        fi
        skip_matrix_construction=true
@@ -117,40 +117,40 @@ while getopts ":hk:t:u:a:i:n:N:f:F:r:o:m:" opt; do
        ;;
     n)
        if [ -n "$param_n" ]; then
-           echo "Error: Cannot combine -n with -f" >&2
-           echo "${USAGE}" >&2
+           echo "ERROR: Cannot combine -n with -f" >&2
+           echo "Try 'muset -h' for more information." >&2
            exit 1
        fi
        if ! is_integer "${OPTARG}"; then
-           echo "Error: -n argument must be an integer." >&2
+           echo "ERROR: -n argument must be an integer." >&2
            exit 1
        fi
        param_n="-n ${OPTARG}"
        ;;
     N)
        if [ -n "$param_N" ]; then
-           echo "Error: Cannot combine -N with -F" >&2
-           echo "${USAGE}" >&2
+           echo "ERROR: Cannot combine -N with -F" >&2
+           echo "Try 'muset -h' for more information." >&2
            exit 1
        fi
        if ! is_integer "${OPTARG}"; then
-           echo "Error: -N argument must be an integer." >&2
+           echo "ERROR: -N argument must be an integer." >&2
            exit 1
        fi
        param_N="-N ${OPTARG}"
        ;;
     f) 
        if [ -n "$param_n" ]; then
-           echo "Error: Cannot combine -f with -n" >&2
-           echo "${USAGE}" >&2
+           echo "ERROR: Cannot combine -f with -n" >&2
+           echo "Try 'muset -h' for more information." >&2
            exit 1
        fi
        param_n="-f ${OPTARG}"
        ;;
     F) 
        if [ -n "$param_N" ]; then
-           echo "Error: Cannot combine -F with -N" >&2
-           echo "${USAGE}" >&2
+           echo "ERROR: Cannot combine -F with -N" >&2
+           echo "Try 'muset -h' for more information." >&2
            exit 1
        fi
        param_N="-F ${OPTARG}"
@@ -161,10 +161,16 @@ while getopts ":hk:t:u:a:i:n:N:f:F:r:o:m:" opt; do
        ;;
     m) minimizer_length=${OPTARG}
        ;;
-    :)  echo -e "Option -${OPTARG} requires an argument\n" >&2
-        echo "${USAGE}" >&2
-        exit 1
-        ;;
+    h) echo "${USAGE}"
+       exit 0
+       ;;
+    v) echo "muset v${MUSET_VERSION}"
+       exit 0
+       ;;
+    :) echo -e "ERROR: Option -${OPTARG} requires an argument\n" >&2
+       echo "Try 'muset -h' for more information." >&2
+       exit 1
+       ;;
     \?) echo "Invalid option: -${OPTARG}" >&2
         echo "Try 'muset -h' for more information." >&2
         exit 1
@@ -188,7 +194,7 @@ if [ "${skip_matrix_construction}" != true ]; then
     fi
 
     input_file=$1
-    
+
     if [ ! -f "$input_file" ]; then
         echo "ERROR: Input file \"${input_file}\" does not exist." >&2
         exit 1
@@ -225,11 +231,11 @@ if [ -z "$param_n" ] && [ -z "$param_N" ]; then
     param_N="-F $frac_samples_present"
 elif [ -z "$param_n" ]; then
     echo "Error: Either -n or -f must be specified." >&2
-    echo "${USAGE}" >&2
+    echo "Try 'muset -h' for more information." >&2
     exit 1
 elif [ -z "$param_N" ]; then
     echo "Error: Either -N or -F must be specified." >&2
-    echo "${USAGE}" >&2
+    echo "Try 'muset -h' for more information." >&2
     exit 1
 fi
 
