replaced -s parameter with -i which accepts the path to the input matrix

diff --git a/bin/muset b/bin/muset
--- a/bin/muset
+++ b/bin/muset
@@ -47,7 +47,7 @@ USAGE:
 
 OPTIONS:
    -h         print this help and exit
-   -s         skip the matrix construction step (Step 1)
+   -i PATH    skip matrix construction and run the pipeline with a previosuly computed matrix
    -k INT     k-mer size (default: 31)
    -a INT     min abundance to keep a k-mer (default: 2)
    -u INT     minimum size of the unitigs to be retained in the final matrix (default: 100)
@@ -83,6 +83,7 @@ frac_samples_present=$DEFAULT_FRAC_SAMPLES_PRESENT
 param_n=""
 param_N=""
 skip_matrix_construction=false
+input_matrix=""
 
 # Function to check if a value is an integer
 is_integer() {
@@ -93,18 +94,23 @@ is_integer() {
     return 0
 }
 
-while getopts ":hs:k:t:u:a:n:N:f:F:r:o:m:" opt; do
+while getopts ":hk:t:u:a:i:n:N:f:F:r:o:m:" opt; do
     case "${opt}" in
     h) echo "${USAGE}" >&2
        exit 0
-       ;;
-    s) skip_matrix_construction=true
        ;;
     k) k_len=${OPTARG}
        ;;
     t) thr=${OPTARG}
        ;;
     u) utg_len=${OPTARG}
+       ;;
+    i) input_matrix="${OPTARG}"
+       if [ ! -f "${input_matrix}" ] || [ ! -s "${input_matrix}" ]; then
+           echo "Input matrix \"${input_matrix}\" is not a file or is empty" >&2
+           exit 1
+       fi
+       skip_matrix_construction=true
        ;;
     o) output_dir=${OPTARG}
        ;;
@@ -154,12 +160,12 @@ while getopts ":hs:k:t:u:a:n:N:f:F:r:o:m:" opt; do
        ;;
     m) minimizer_length=${OPTARG}
        ;;
-    \?) echo "Invalid option: -$OPTARG" >&2
+    :)  echo -e "Option -${OPTARG} requires an argument\n" >&2
         echo "${USAGE}" >&2
         exit 1
         ;;
-    :)  echo "Option -$OPTARG requires an argument." >&2
-        echo "${USAGE}" >&2
+    \?) echo "Invalid option: -${OPTARG}" >&2
+        echo "Try 'muset -h' for more information." >&2
         exit 1
         ;;
     esac
@@ -208,7 +214,7 @@ echo "Minimum abundance (-a): ${min_kmer_abundance}"
 echo "Input file: ${input_file}"
 
 # Echo if the matrix construction flag was set
-echo "Skip matrix construction flag (-s) was set: $skip_matrix_construction"
+echo "Skip matrix construction (-s): ${skip_matrix_construction}"
 
 # Check for default settings if -n, -N, -f, -F, are not set
 if [ -z "$param_n" ] && [ -z "$param_N" ]; then
@@ -230,21 +236,27 @@ echo "Basic filter settings: $param_n $param_N"
 start=$(date +%s%3N)
 
 # Step 1: Produce sorted input k-mer matrix from fof.txt file unless -s flag is set
-if ! $skip_matrix_construction; then
+if [ "${skip_matrix_construction}" != true ]; then
     log_and_run kmtricks pipeline --file $input_file --kmer-size $k_len --hard-min ${min_kmer_abundance} --mode kmer:count:bin --cpr --run-dir $output_dir -t $thr --recurrence-min $rec_min
     log_and_run kmtricks aggregate --matrix kmer --format text --cpr-in --sorted --output $output_dir/sorted_matrix.txt --run-dir $output_dir -t $thr
+    input_matrix="${output_dir}/sorted_matrix.txt"
 else
-    echo "Step 1 is skipped due to -s flag"
+    echo "Skipped matrix construction. Using matrix provided in \"${input_matrix}\""
+    mkdir -p "${output_dir}"
 fi
 
-# Check if $output_dir exists and if sorted_matrix.txt is not empty:
-if [ ! -d "$output_dir" ] || [ ! -s "$output_dir/sorted_matrix.txt" ]; then
-    echo "Error: The output directory $output_dir does not exist or the sorted_matrix.txt file is empty." >&2
+if [ ! -d "${output_dir}" ]; then
+    echo "Error: The output directory $output_dir does not exist." >&2
+    exit 1
+fi
+
+if [ ! -f "${input_matrix}" ] || [ ! -s "${input_matrix}" ]; then
+    echo "Matrix file \"${input_matrix}\" does not exist or is empty." >&2
     exit 1
 fi
 
 # Step 2: Perform some basic filtering
-log_and_run kmat_tools filter $output_dir/sorted_matrix.txt -a ${min_kmer_abundance} $param_n $param_N -o $output_dir/sorted_filtered_matrix.txt
+log_and_run kmat_tools filter "${input_matrix}" -a ${min_kmer_abundance} $param_n $param_N -o $output_dir/sorted_filtered_matrix.txt
 
 # Check if filter was too stringent
 if [ ! -s "$output_dir/sorted_filtered_matrix.txt" ]; then
